name: Deploy to Hostinger

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.ikromshi.com  
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
        server-dir: /home/u115467450/domains/ikromshi.com/public_html/sd/

